export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const MENU = {
    TOGGLE_MENU: 'MENU.TOGGLE_MENU',
    SET_ACTIVE_STATE: 'MENU.SET_ACTIVE_STATE'
};